### ISSUE TITLE
Seeking permission to grab a documentation change

### ISSUE THREAD

**Issue by bmah888** [andybalholm/spamass-milter#1]
Hi!  I maintain the spamass-milter port for FreeBSD (I don't know much about it, but I do use it).  Recently a FreeBSD user asked me about updating the port to include the documentation change for the `-a` option which is contained in revision 97b2369ea24f1370bbf3359a0fbcdc6670a54da0 in this repository.  This would involve committing the diff for the manpage into the FreeBSD ports tree.  I just wanted to reach out and confirm that this would be OK (I know you published the change in a public Git repository that itself is a copy of a project that's supposedly GPLv2 licensed, but just wanting to at least check with you).

Thanks!

**Comment by andybalholm** [comment]
Yes, that's fine. My intention is for my changes to be distributable under the same license as the original repository.
