### ISSUE TITLE
fork status is unclear

### ISSUE THREAD

**Issue by gdt** [andybalholm/spamass-milter#10]
I have been maintaining the spamass-milter port in NetBSD and was just reminded about this repository.   The README says that the project is on savannah.nongnu.org, and given that there are recent commits here (unlike the official repo), it would seem that this is some kind of continuation/fork.   I don't mean to criticize that at all, but it would be really helpful if the fork status was clear in the README, including the relationship with upstream (e.g., if upstream hasn't answered mail about updates,  that's relevant).

Separately from this issue, if this is a fork, it would be nice to apply all the accumulated patches over the years and have an actual release, so that packaging systems can update to it.

**Comment by andybalholm** [comment]
I'm wondering what came of your plans to start maintaining the upstream a little bit, which came out of the discussion on the spamass-milt mailing list about the time you filed this issue.

**Comment by gdt** [comment]
Well, basically every day I don't.   I consider myself reminded...
