### ISSUE TITLE
confMILTER_MACROS_ENVRCPT should probably not contain {b} macro

### ISSUE THREAD

**Issue by sborrill** [andybalholm/spamass-milter#9]
Your README says:
confMILTER_MACROS_ENVRCPT must include the {b}, {r}, {v}, and {Z} macros

However, it appears as though including {b} can lead to false positives on DATE_IN_FUTURE_96_Q:

https://muug.ca/pipermail/roundtable/2016-February/004537.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775183#30

It should be in confMILTER_MACROS_CONNECT or confMILTER_MACROS_ENVFROM, but not confMILTER_MACROS_ENVRCPT

**Comment by andybalholm** [comment]
I don't know how to configure sendmail; I use postfix myself. But if you're sure about the change, go ahead and submit a pull request.

**Comment by kees-closed** [comment]
> I don't know how to configure sendmail; I use postfix myself. But if you're sure about the change, go ahead and submit a pull request.

And how can this be configured in Postfix? The error seems to include sendmail specific configuration hints, not Postfix. There are some macro variables listed by `postconf`. But I don't want to guess there. Do you have more information?

I guess the answer is in `/usr/share/doc/spamass-milter/README.Debian.gz`?

```
--------------------------------------------------------------
  Integrating spamass-milter into your postfix installation
--------------------------------------------------------------

You need to edit /etc/postfix/main.cf and configure smptpd_milters so
that postfix connects to the spamass-milter socket. Something like:

  # spamass-milter configuration
  smtpd_milters = unix:/var/spool/postfix/spamass/spamass.sock

should work. Note, however, if you're using a chrooted version of
postfix, you'll need the local path to the socket inside of the
chroot. In recent versions of Debian the following should work:

  # spamass-milter configuration
  smtpd_milters = unix:/spamass/spamass.sock
  # milter macros useful for spamass-milter
  milter_connect_macros = j {daemon_name} v {if_name} _
  milter_data_macros = j i {auth_type} {daemon_name} v {if_name} _
  milter_rcpt_macros = j {auth_type} {daemon_name} v {if_name} _

See http://www.postfix.org/MILTER_README.html or
/usr/share/doc/postfix/MILTER_README.gz (in postfix-doc) for
information on how to set tempfail and the various timeouts that the
sendmail configuration above uses.

The defaults for spamass-milter adjust themselves so that no
configuration in /etc/default/spamass-milter should be required.
[However, if you are not doing so, see below.]
```

Even with the above macros in main.cf I get this macro error (using Debian 11). Or is this an error I can ignore? Since I'm not using Sendmail.

**Comment by andybalholm** [comment]
The issue seems to be a Sendmail-specific bug, where Sendmail gives the milter the wrong date. Are you seeing problems in Postfix too?

**Comment by kees-closed** [comment]
@andybalholm true, it's about Sendmail. I usually want to solves errors. If it was a warning I would've ignored it. But it ends up in `/var/log/mail.err`. I don't know if it really causes issues. Should those milter macro settings in the Debian README be applied anyway? Or is it safe to ignore this warning on Postfix?

Edit: I see by the way I wasn't awake, the error I encounter is different:
```
spamass-milter[183209]: Could not retrieve sendmail macro "b"!.  Please add it to confMILTER_MACROS_ENVRCPT for better spamassassin results
```

**Comment by andybalholm** [comment]
I would definitely try the recommended macro configuration, and see if it helps.

**Comment by kees-closed** [comment]
> I would definitely try the recommended macro configuration, and see if it helps.

I've tried it, but didn't change the error. I also read [this explanation](https://bugzilla.redhat.com/show_bug.cgi?id=1368645#c7), but I rather take advice from the devs themselves.

**Comment by andybalholm** [comment]
It looks like that problem is unavoidable with Postfix. Maybe the log message should just be removed.

**Comment by ecxod** [comment]
I also have the failure in mail.err, every time I receive a email.
```
spamass-milter[xxxx]: Could not retrieve sendmail macro "b"!.  Please add it to confMILTER_MACROS_ENVRCPT for better spamassassin results
```
'b' is used to fetch the timestamp that gets put in the Received header, so it's used for every message. And I notice that at least in my case the Received header contains a timestamp, so there are 2 possibilities : 
- macro b is loaded but some detection system is not taking correct note of that, and is throwing a wrong error.
- macro b is not necessary, because some other method is getting the timestamp, and the code that throws the error can be removed safely.

**Comment by andybalholm** [comment]
What MTA are you using (sendmail, postfix, or something else)? Postfix doesn't seem to support the "b" macro. Since almost everyone who is using spamass-milter is using it with postfix at this point, I would be open to a pull request that removes that log message.
